[project]
name = "termidex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "textual>=6.4.0",
]

[dependency-groups]
dev = [
    "textual-dev>=1.8.0",
]
